# The name of your plugin as displayed in the Traefik Pilot web UI.
displayName: WebsitePathConverter

# For now, `middleware` is the only type available.
type: middleware

# The import path of your plugin.
import: github.com/florentinl/websitepathconverter

# A brief description of what your plugin is doing.
summary: Tampers the path of the request to convert it to serve a website.


# Configuration data for your plugin.
# This is mandatory,
# and Traefik Pilot will try to execute the plugin with the data you provide as part of its startup validity tests.
testData:
  Directory: /mywebsite
